const moods = [
    { clazz: "happy-mood", name: "Happy" },
    { clazz: "stressed-mood", name: "Stressed" },
    { clazz: "tired-mood", name: "Tired" },
    { clazz: "sad-mood", name: "Sad" },
    { clazz: "anxious-mood", name: "Anxious" },
    { clazz: "relaxed-mood", name: "Relaxed" },
    { clazz: "angry-mood", name: "Angry" },
    { clazz: "excited-mood", name: "Excited" },
    { clazz: "bored-mood", name: "Bored" },
    { clazz: "confident-mood", name: "Confident" },
    { clazz: "joyful-mood", name: "Joyful" },
    { clazz: "grateful-mood", name: "Grateful" },
    { clazz: "optimistic-mood", name: "Optimistic" },
    { clazz: "peaceful-mood", name: "Peaceful" },
    { clazz: "in-love-mood", name: "In love" },
    { clazz: "hopeful-mood", name: "Hopeful" },
    { clazz: "frustrated-mood", name: "Frustrated" },
    { clazz: "nostalgic-mood", name: "Nostalgic" },
    { clazz: "melancholic-mood", name: "Melancholic" },
    { clazz: "surprised-mood", name: "Surprised" },
    { clazz: "other-mood", name: "Other" },
];